### ISSUE TITLE
Both upper left and upper right are still white in dark mode when enable shrink 

### ISSUE THREAD

**Issue by chaoticlonghair** [EnixCoda/Gitako#124]
![image](https://user-images.githubusercontent.com/30993023/106561243-4cd30e80-6563-11eb-8a50-c09cc427277e.png)

I only test with Gitako v2.6.2 on Firefox v78.7.0esr.
It works well if disabled the shrink mode.

**Comment by EnixCoda** [comment]
Thanks for the feedback.

The shrinking header feature is experimental and not removed for legacy support. I'll consider deprecate it if it no longer works well.

**Comment by chaoticlonghair** [comment]
IMHO, update the follow background to `--gitako-header-bg` or `--color-header-bg` could fix it.

https://github.com/EnixCoda/Gitako/blob/95a258a9b943f30a52b0f7784229cc6cf5336dd3/src/styles/index.scss#L25

<small>I have no experience of `TypeScript` or `SCSS`, I only test it with Firefox Developer Tools.</small>

**Comment by EnixCoda** [comment]
Yes, patching on this issue again is not hard, it could be as easy as your 1-liner CSS suggestion. But from my experience of maintaining Gitako so far, I've found that hacking styles of GitHub is not only a dirty work but also not what Gitako should be focused on. That's why I am passive about fixing this again.

**Comment by EnixCoda** [comment]
Done with 1588a903c216a166f9bdb2cb75323d8050087320 in `v2.7.0`
