### ISSUE TITLE
Gitako blocks forward & backwards actions of Logitech mouse

### ISSUE THREAD

**Issue by razbensimon** [EnixCoda/Gitako#154]
I have a very strange issue for a long time now.
For some reason, suddenly my forwards & backwards buttons in my mouse stopped work.
Today I realized that `gitako` extension is the reason why.

before `gitako` render its DOM element, the buttons work fine.
![image](https://user-images.githubusercontent.com/5955905/121890040-9528e700-cd22-11eb-8e51-5fb6fbf16694.png)
after the render complete, it blocks the events of forward & backwards.
In addition, I tried to disable the extension and it worked too.

Can you identify the issue? I really like this extension but it makes me crazy that I must click chrome's UI buttons to make a trigger for forward/backwards action.

**Comment by EnixCoda** [comment]
Hi @razbensimon 

Gitako does capture browser history manipulation events(backward, forward, etc) to enable PJAX to optimize your navigating experience.

Generally, your mouse's buttons that trigger forwards&backwards are mapped to some keyboard shortcuts. Could you inspect what the shortcut is using the mouse's utility software? So that I can make further investigations.

**Comment by razbensimon** [comment]
@EnixCoda thanks for the quick response.

Generally, my mouse has just Forward & Back triggers - which I don't know how chrome translate.
![image](https://user-images.githubusercontent.com/5955905/121904168-a1687080-cd31-11eb-8d2b-06a0b93e39b0.png)

But `gitako` blocks it even with a workaround that I tried - I re-mapped those buttons to do `Cmd + ArrowLeft` & `Cmd + ArrowRight` respectively. Those the chrome's shortcuts for Back & Forward.

* note that the Mac CMD button is a Meta button on js.

**Comment by EnixCoda** [comment]
Thank you! I can reproduce it issue now.

Cmd + ArrowLeft & Cmd + ArrowRight would be blocked when the sidebar is focused in order to allow navigating between sidebar file tree items. And the sidebar would be focused after redirecting. But the behavior was not expected to happen when the sidebar is not expanded.🤔

I will optimize the logic of this part.

BTW, I have made a simple page for inspecting the key. You can focus on the input field and press the buttons to see what keys they are mapped to. Please let me know if they are not `Cmd + ArrowLeft/ArrowRight`
https://jt50f.csb.app/

**Comment by razbensimon** [comment]
> But the behavior was not expected to happen when the sidebar is not expanded.🤔

True. thanks.

And your 'keypress' listener works as expected when I force map the mouse button to execute a keyboard shortcut:
![image](https://user-images.githubusercontent.com/5955905/121959167-160cd080-cd6d-11eb-9a9a-6484fd0969a8.png).

Maybe if you fix it I can live with that, but it is a workaround. Hopefully it will fix also the "real" mouse button triggers.
(I cant test it with your code - Forward triggers nothing, no 'keypress' event. and Back makes chrome go back 😆 )

**Comment by razbensimon** [comment]
So i think i found a lead here. 
https://sensible-side-buttons.archagon.net/ (look at Technical Notes section)

Very interesting implementation of Logitech Back & Forward. Looks like it just fake mac swipe gestures - so no keypress event. so you can probably debug with it if you don't have MX Master.

**Comment by EnixCoda** [comment]
Interesting technical insights of the tool!

> so no keypress event

If so, my assumption on the keypress event capturing should be wrong.

I'll make more investigation with the tool. Thank you very much! 😃

**Comment by EnixCoda** [comment]
I got a Logitech G703 recently and its default side button actions are back & forward navigation. Those buttons are not mapped to key press actions so I believe they are also implemented with swipe gestures like https://sensible-side-buttons.archagon.net/ as introduced.
The buttons worked well on all sites I tested including github.com with Gitako enabled. I believe this issue should have been fixed.
