### ISSUE TITLE
PJAX not working for legacy GitHub enterprise

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#189]
Will add an option to fallback PJAX mode in the settings.

**Comment by EnixCoda** [comment]
@kidonng Could you please provide some insights of picking `#repo-content-pjax-container` instead of `#js-repo-pjax-container` in #177 ?

https://github.com/kidonng/Gitako/blob/8a3135a312f84f65a5d2b94956dd97d7cb520947/src/components/MetaBar.tsx#L33

I am planning to set `data-pjax="#repo-content-pjax-container, #js-repo-pjax-container"` to extend its compatibility to address this issue.

In legacy GitHub enterprise, `#repo-content-pjax-container` may match nothing and result in PJAX failure.

Thanks!

**Comment by EnixCoda** [comment]
Done in f88d7c0575fbb28b6bbbbbb2690102422de430c3

**Comment by EnixCoda** [comment]
Found problem when redirecting from PR conversations tab to files tab via clicking Gitako file tree items if using both selectors. Added fallback logic to use single selector to support both github.com and GitHub enterprise.

**Comment by kidonng** [comment]
> @kidonng Could you please provide some insights of picking `#repo-content-pjax-container` instead of `#js-repo-pjax-container` in #177 ?

Sorry for the late reply. The reason is simple: `#repo-content-pjax-container` does not contain the header while `#js-repo-pjax-container` does. It is also what GitHub's tab bar is using:

<img width="541" alt="Screen Shot 2022-02-20 at 18 23 35" src="https://user-images.githubusercontent.com/44045911/154838226-3b3d1590-d429-49a6-83bd-c18ed65ccef0.png">

I'm surprised if something this fundamental is different in GHE. But all's well that ends well.
