### ISSUE TITLE
Firefox OAuth access denied for private repos.

### ISSUE THREAD

**Issue by jackys-95** [EnixCoda/Gitako#223]
Using the extension v3.6.2 with Firefox 99.0b8 (64-bit), I get this following errors:
```
Gitako: The OAuth token may have expired, please try again.
```
<img width="249" alt="accessdenied" src="https://user-images.githubusercontent.com/9795086/160324622-4489085a-e704-4ec8-9007-101696a1e65f.png">

I've already granted the app OAuth permissions which is visible from GitHub `Settings -> Applications -> Authorized OAuth Apps`.  I've tried disabling uBlock Origin and Firefox's tracking protections for GitHub, as well as toggling on `Enable Gitako for this domain` but the error message remains.

For what it's worth, I was able to get the plugin working on Edge 99.0.1150.55, which essentially has default settings and uBlock Origin enabled. Is there something I'm missing to get it working on Firefox?

**Comment by EnixCoda** [comment]
Thank you @jackys-95 

I can reproduce this issue on my Firefox. Will try to fix ASAP.

**Comment by EnixCoda** [comment]
After a quick investigation, the issue is caused by vercel.app. It forces redirecting requests from `now.sh` to `vercel.app` domain. And `vercel.app` is not a valid domain for Gitako to request in Firefox. It is not listed in the `manifest.json` and Firefox has a more strict limit for extensions than other browsers.

The good news is that it should not affect Chrome and Edge.
But to fix this, the `manifest.json` file has to be updated. Then all Firefox users would have to re-enable Gitako manually due to its change.

Perhaps I should make the update together with upgrading manifest.json to v3 so that users would not need to re-enable Gitako 2 times.

**Comment by EnixCoda** [comment]
Made some attempt in migrating to manifest v3 and found its spec & doc not fully ready for Gitako's requirements. For example, the workflow of requesting permission under dynamic host is not as friendly as the current.

As this issue has been open for 1 month and the problem may have existed for even longer time. I'd delay upgrading manifest v3 for a few months and release a patch version for this issue now.

Instead of `vercel.app`, I replaced `now.sh` with `enix.one`. It is owned by myself, thus more stable.

New version `3.7.0` will be available in 24hrs.
