### ISSUE TITLE
Auto focus search box when expanding sidebar

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#256]
When the sidebar is expanded (either automatically or via shortcuts), it would be ideal to focus the search box automatically so users can start searching immediately.

**Comment by EnixCoda** [comment]
Thanks for reminding me. Not sure if this feature was removed during the last large scope refactor. ~Or it was implemented in my imagination? 🫢~

There will be an improvement in accessibility & usability next time, including an enhancement for this.

**Comment by EnixCoda** [comment]
A keyboard shortcut setting for focusing search input has been added in `v3.9.0`. Instead of applying auto-focus to search input. Because 

1. The file explorer needs to be auto-focused so that the active element of the file list will be preserved. Users can continue browsing files after toggling Gitako's sidebar.
2. If a user is going to use search input, he/she has to use the keyboard to type. So I suppose adding a keyboard shortcut would be convenient and not conflict with `1`.
