### ISSUE TITLE
Options to disabling resizing

### ISSUE THREAD

**Issue by mon-jai** [EnixCoda/Gitako#268]
I sometimes resize the panel accidentally and there is no way to reset sidebar width to default value.

It would be better if we could disable the resize slider in Settings.

**Comment by EnixCoda** [comment]
> there is no way to reset sidebar width to default value

Please double-click on the resize slider to reset. This is a hidden feature.

My concern about disabling resize is that when a user visits a large repo, the user could find lots of items not visible due to truncation. The user would have to re-enable it again and enlarge the panel. That could not be very pleasant.

You are welcome to raise a vote for this feature in [the discussions section](https://github.com/EnixCoda/Gitako/discussions). I'd implement anyway it if enough users need it. :)
