### ISSUE TITLE
`pinned` icon style

### ISSUE THREAD

**Issue by thilllon** [EnixCoda/Gitako#283]
Hi,
Thanks for the amazing extension.

I think it looks better if the `pinned` icon style would be changed when it is activated

Before:

outlined style

![image](https://user-images.githubusercontent.com/44559468/216805174-da023417-d6b3-4876-bdb9-84ef8f21030d.png)

After(expected):

filled style

![image](https://user-images.githubusercontent.com/44559468/216805210-63a4b9ac-8de9-4a8b-865c-d3fc5fdc3d5b.png)

**Comment by EnixCoda** [comment]
Thanks, @thilllon 

Yes, it does look better that way, with higher contrast so that users can tell the status easier.

Reasons it is not in filled style:
- The most important reason: Gitako's icon are from [Octoicons](https://primer.style/octicons/), which does not offer an filled version for the pin icon.
- Apart from its slight color change. Currently users can tell the status from the existence of the collapse icon next to it.
- It is easy to tell if the panel is pinned without even looking at the icon. Because when it is not pinned, Gitako would be collapsed before mouse hovers. Otherwise, it is apparently pinned.

Anyway, I will be happy to apply the filled style pin icon once it is available!
