### ISSUE TITLE
This extension has a bug on the high score screen

### ISSUE THREAD

**Issue by Nioy** [EnixCoda/Gitako#30]
This extension has a bug on the high score screen.My monitor is 27-inch 2k resolution, which will be displayed every time I enter.
![图像 2](https://user-images.githubusercontent.com/13707298/57571617-e929b900-7442-11e9-8004-fac091267351.jpg)

**Comment by EnixCoda** [comment]
Hi, @Nioy !
So you expected it to be positioned at the *left side* of page instead of current *centered* layout?

Actually I implemented Gitako to be attached to page's content on purpose. I think in this way users do not need to move their eyes between left and center. The UX would be better.

But your suggestion is absolutely reasonable! Other well know extensions like Octotree are implemented in the way you expected.

 I'll consider add an option to toggle the position of Gitako anyway!

Thank you!

**Comment by EnixCoda** [comment]
New layout has been implemented, will release in few days!
