### ISSUE TITLE
Doesn't work with custom repos

### ISSUE THREAD

**Issue by Tyson1986** [EnixCoda/Gitako#34]
Hi. We have custom enterprise Github with DNS like: github.my.company.com
The extension doesn't render the tree on the left side. Looks like it doesn't understand that current page is a github page.

**Comment by EnixCoda** [comment]
Hi, Tyson

Thank you for using Gitako and giving a feedback!

For now, Gitako do not recognize domains other than `github.com`. I'll try to bring Gitako to enterprise GitHub and let you know when it's available.

**Comment by leocaseiro** [comment]
Hi, this extension helps to enable it https://github.com/fregante/webext-domain-permission-toggle

**Comment by vcfvct** [comment]
Great extension! 👍 
Would be great if it comes with `GH Enterprise` support.

**Comment by EnixCoda** [comment]
One thing blocking me from implementing this feature:

I do not have accounts for GitHub enterprise so that I cannot develop and test for it :(

**Comment by leocaseiro** [comment]
I managed to enable the extension in the GH enterprise, but I still some work to do for the OAuth token to show the files and directories.

**Comment by leocaseiro** [comment]
It's working fine now if I create my personal token and paste it, but I need to replace some URLS:

from **//api.github.com/** to **//enterpriseurl.something/api/v3/**

and some of the links:

from **//github.com/** to **//enterpriseurl.something/**

Maybe, I'll convert to an URL.

If you don't mind @EnixCoda, I would like yout inputs on the best practices to follow, thanks

**Comment by leocaseiro** [comment]
Lastly, I wonder if we need to replace the API from v3 to v4 as v3 is deprecated.

**Comment by EnixCoda** [comment]
Hi @leocaseiro 

Actually I've made some progress on making Gitako work on sites other than GitHub during last months, but did not push to GitHub. Now it is pushed at `feature/enterprise`.

I checked out your fork, it looks like our changes are quite similar while mine have some minor changes so that Gitako could work on browsers other than Chrome after the changes. It seems that we are very close to support GH enterprise!

The API changes on enterprise domains you mentioned are very valuable! I'll work on adapting to that myself. Many thanks for you help!

One more thing, for replacing v3 with v4, I prefer not working on that as long as v3 is not really going to be deprecated, actually I could not find announcements about that. And, AFAIK, v4 (GraphQL) is not completely better than v3, for example, it is not easy to retrieve whole tree structure in v4 as that needs recursive query.

**Comment by EnixCoda** [comment]
There is a pre-release version at https://github.com/EnixCoda/Gitako/releases/tag/release-enterprise-aaf6466

Could anyone help me download and test it?

Known issues:
- OAuth is not ready

**Comment by EnixCoda** [comment]
Maybe OAuth won't be available for enterprise.

If anyone could access GitHub enterprise, please access `https://{enterprise.host}/settings/connections/applications/0c85caf6f97983d6e27a` to see if Gitako is available to the enterprise version and let me know.

**Comment by yuezk** [comment]
@EnixCoda 

I tried with the pre-release, but it didn't work on the enterprise GitHub. (github.xxx.com)
 
Do I need any extra configuration?

**Comment by EnixCoda** [comment]
Thanks for reaching out @yuezk

You need to right click on Gitako's icon, then on `Enable Gitako on this domain` and refresh the page.

![image](https://user-images.githubusercontent.com/7480839/81154484-87991d80-8fb6-11ea-999c-13e0506acb66.png)

**Comment by EnixCoda** [comment]
If it failed, please take a screenshot of browser devtool's console. That'll be very helpful.

**Comment by yuezk** [comment]
Still failed, below is the screenshot.

![image](https://user-images.githubusercontent.com/3297602/81159547-a5b54c80-8fbb-11ea-94a9-c59af19fd702.png)

**Comment by EnixCoda** [comment]
Interesting, looks like Gitako cannot work on enterprise without access token set. But we managed to access the right API as the status code is 401 instead of 404.

@yuezk Would you create a personal access token and paste into Gitako to give another try?

You can refer to [wiki](https://github.com/EnixCoda/Gitako/wiki/Access-token-for-Gitako#manually). You might find tokens page at `https://github.your.host/settings/tokens`.

**Comment by yuezk** [comment]
It worked after I set the access token.

BTW, I encountered some problems while enabling this plugin:

1. The input field of the access token is not visible when it failed to connect to GitHub, only one icon is visible. I have to use Chrome DevTools to make it visible, it's a bit of tricky for normal users.
 
  ![image](https://user-images.githubusercontent.com/3297602/81165041-e5803200-8fc3-11ea-8a0b-fdfc8e27570d.png)
2. The token didn't separate by domain, because once I set up the token on the enterprise site, I cannot use it on the official site (https://github.com).
3. The VSCode icons are broken.
  ![image](https://user-images.githubusercontent.com/3297602/81166369-2bd69080-8fc6-11ea-9e09-18299ec009d8.png)

**Comment by EnixCoda** [comment]
@yuezk 

`1.` is a confirmed bug and have been fixed today in `v1.3.3`.

I'll fix `2.` and `3.` then release another build for enterprise. Thanks!

**Comment by EnixCoda** [comment]
https://github.com/EnixCoda/Gitako/releases/tag/release-enterprise-83aca3e

Fixed issues mentioned above, except `3.` mentioned by @yuezk 

I cannot reproduce it locally. Are VSCode icons also broken on `github.com` for you?

**Comment by yuezk** [comment]
It works now, for both enterprise and non-enterprise sites.

For the VSCode icons, it's a build problem. I have to clone the vscode-icons first before I run `yarn build`. So, it should not matter.

**Comment by EnixCoda** [comment]
@yuezk I see

Thank you for your generous help! Enterprise version should be published soon!

**Comment by EnixCoda** [comment]
Gitako v2.0 with GitHub enterprise support is under review in extension stores.

Thanks to everyone gave me a hand on this!
