### ISSUE TITLE
[feature request] add switch branch function

### ISSUE THREAD

**Issue by batkiz** [EnixCoda/Gitako#49]
Could Gitako support branch switching in it?

**Comment by EnixCoda** [comment]
Hi @batkiz 
I thought of this feature before but abandoned. Because I found that for most scenarios users want to switch branch, user usually be under the code tab. And if user is under the code tab, there will be a tab switcher provided by GitHub, which even supports searching and tags!

If you have any other detailed reasons, please tell me more!

**Comment by batkiz** [comment]
I don't have more reasons, thanks for your reply. 
~~In fact this feature is rarely used among users(~~
