### ISSUE TITLE
Chrome Web Store link doesn't works

### ISSUE THREAD

**Issue by joasgarcia** [EnixCoda/Gitako#51]
https://chrome.google.com/webstore/detail/gitako/giljefjcheohhamkjphiebfjnlphnokk
![image](https://user-images.githubusercontent.com/6011412/77429990-3d1e6180-6db9-11ea-8391-8f81aad53651.png)

**Comment by EnixCoda** [comment]
@joasgarcia Thanks for feedback.

Actually I released next version of Gitako on Chrome web store **few weeks ago** but it has always been pending review status. And I clicked on `Unpublish` yesterday accidentally and found there was no way to republish it in web store developer dashboard due to the latest version is pending review :(

It seems that I have to wait for Gitako v1.0 to be reviewed.

**Comment by xCss** [comment]
webstore什么时候通过啊，chrome等待中。。。~

**Comment by EnixCoda** [comment]
@xCss 不知道，被卡住的还是重要的 1.0 版。我很难受。

不介意的话请到 release 页下载 zip 版，通过开启 Chrome extensions developer mode 使用——
https://github.com/EnixCoda/Gitako/releases

**Comment by xCss** [comment]
好吧，请问解压后+开发模式打开后应该怎么操作？

**Comment by EnixCoda** [comment]
@xCss 

https://github.com/EnixCoda/Gitako/wiki/Manually-Install

为了顺便帮助其他用户，令整个流程更顺利，我做了一个 wiki page

**Comment by xCss** [comment]
@EnixCoda 可以可以，不过1.x的版本没有看到zip啊~

**Comment by EnixCoda** [comment]
@xCss  晚些时候会上传一下，届时会在这个 issue 通知～

**Comment by xCss** [comment]
@EnixCoda 收到~

感谢~~:smile:

**Comment by EnixCoda** [comment]
zip of v1.0.1 uploaded

https://github.com/EnixCoda/Gitako/releases/tag/v1.0.1

@xCss

**Comment by EnixCoda** [comment]
CWS sent me this.

![image](https://user-images.githubusercontent.com/7480839/77872313-39875080-7279-11ea-89c2-c5f4b882b7e2.png)

**Comment by EnixCoda** [comment]
v1.0 is finally published!
Download link for CWS on homepage works now!
