### ISSUE TITLE
[Feature] Add option to close by default

### ISSUE THREAD

**Issue by anihm136** [EnixCoda/Gitako#54]
I'd find it useful to have the file tree closed/minimised by default, so that I can open it only when I need.

**Comment by EnixCoda** [comment]
Hi @anihm136 
If you disable `Intelligent Toggle` in settings, Gitako will remember its last open state. So won't open automatically after you close it. Also, you can make it easier to close Gitako by setting up shortcut keys.

I'll keep this issue open for more thumbs up before implementation.

**Comment by anihm136** [comment]
Thanks! I've already set up a shortcut, didn't know about the intelligent toggle setting though. And that was a blazing fast reply!

**Comment by anihm136** [comment]
Hey, I don't seem to have the `Intelligent Toggle` option anymore. Was it removed recently?

**Comment by EnixCoda** [comment]
@anihm136 Hi, I've reorganized settings layout and `Intelligent Toggle` has been renamed and moved to `Toggle Sidebar` section

![image](https://user-images.githubusercontent.com/7480839/78957475-0023d000-7b18-11ea-8fe9-8cdf9b6c256f.png)

Sorry for the inconvenience, I did this because it makes more sense to new users :P

**Comment by anihm136** [comment]
Ah, must've missed it. No problems, as long as it's still there😁
