### ISSUE TITLE
Error: "some thing went wrong"

### ISSUE THREAD

**Issue by kevin7lou** [EnixCoda/Gitako#59]
When I access some repositories, Gitako randomly display the error message "some thing went wrong.", or show the red cross at the right top corner. In this case, I have to refresh the page once or several times until it works with the blue icon.

Any suggestion for me to provide more information to debug? Thanks!
![D-Chat_20200410132009](https://user-images.githubusercontent.com/1493360/78966216-c65fc300-7b31-11ea-8eaa-4ebc82a6e74e.png)

**Comment by EnixCoda** [comment]
Hi @kevin7lou 

This issue should have been fixed in the latest release(v1.2.0). Could you check your local version and update if it outdates? You can see it at bottom left corner of Gitako sidebar or in `chrome://extensions` page.

This is indeed a serious bug though. Gitako has lost some new users due to this in the last release :(. I hope such thing not happen anymore.

Please check your local version number and let me know if it is v1.2.0, that really helps me a lot! And thank you for your feedback!

**Comment by kevin7lou** [comment]
Thanks for your quick reply, @EnixCoda !
Yes, my current version is v1.2.0, and was installed from Chrome Store. Would you pls fix this issue? Thanks!

**Comment by EnixCoda** [comment]
@kevin7lou And this is still happening? That's weird.

I'll give explicit network error description on next release to help fix this.

Or if you'd like to help, please send me a screenshot of browser devtools console when this happens. Many thanks!

**Comment by kevin7lou** [comment]
Sure, I'd like to contribute to your work 😃

**Comment by kevin7lou** [comment]
The issue appears again when I access to https://github.com/nndl/nndl.github.io

**Comment by kevin7lou** [comment]
> @kevin7lou And this is still happening? That's weird.
> 
> I'll give explicit network error description on next release to help fix this.
> 
> Or if you'd like to help, please send me a screenshot of browser devtools console when this happens. Many thanks!

Hi @EnixCoda , would you pls help to make me know how I can export the essential error message what you need for fixing, when the issue appears again? Thanks!

**Comment by EnixCoda** [comment]
I expected to get such screenshots from you when this happens and you

1. open devtool by right-click on webpage, choose `inspect`
1. switch to the `console` tab
1. take screentshot

![image](https://user-images.githubusercontent.com/7480839/80712338-710d4500-8b24-11ea-89b5-8b99b421aded.png)

And as you can see, I happened to have this error occur on my side when I come to reply your comment!

For the case in my screenshot, the reason is that connection got aborted (see `net::ERROR_CONNECTION_REDUSED`). And I notice that I am accessing GitHub without proxy (I rarely turn it off). So the answer is clear, it is network issue.

If you are in mainland China accessing GitHub without a proxy, please consider have one. Or the next it happens, take such screenshots to me.

Thank you!

**Comment by EnixCoda** [comment]
Hi @kevin7lou

Did `some thing went wrong` show up these days?

**Comment by kevin7lou** [comment]
> Hi @kevin7lou
> 
> Did `some thing went wrong` show up these days?

so far so good! And I think you are right, and the root cause is about the network issue.

**Comment by EnixCoda** [comment]
@kevin7lou Great! Closing this issue.
