### ISSUE TITLE
A max of 64 subdirectories are visible in the tree

### ISSUE THREAD

**Issue by NickDrouin** [EnixCoda/Gitako#87]
Browse to:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk

Expected:
I can see past 'network' folder in the sdk subfolder.

Actual:
Only the first 64 folders are listed.
Searching for a folder, or files within a folder, past the 64th: give no results.

v2.3.0

**Comment by EnixCoda** [comment]
Thank you for the feedback! This is really an interesting issue.

I went to https://github.com/DefinitelyTyped/DefinitelyTyped, which has more files and folders, to see if it is due to GitHub has set up limitations to the response size, but Gitako worked well there. I'll dig deeper into it later!

**Comment by EnixCoda** [comment]
Hi, @NickDrouin 

Update: It turns out that its GitHub's API not responding complete list of files in that repo caused this issue, it is truncated. Maybe Gitako should load files async if the repo has too many files. I'll try to find the answer to detecting the size when given a repo then.

---

I looked up for `sdk/network` and `sdk/parents` in the response of the [endpoint for retrieving file list](https://api.github.com/repos/Azure/azure-sdk-for-java/git/trees/master?recursive=1). The `sdk/parents` is one of the folders that exist in the repo but not shown up in Gitako's file tree.

![image](https://user-images.githubusercontent.com/7480839/94508647-fb2d1700-0244-11eb-8959-c1162d32e6a1.png)

![image](https://user-images.githubusercontent.com/7480839/94508464-9b367080-0244-11eb-9c7c-e4b1027ecadd.png)

As we can see, there are no files under `sdk/parents` in the response at all. ~I'll feedback this to the GitHub team then.~

Thank you anyway 😁

**Comment by EnixCoda** [comment]
Now I have made a plan for fixing it. Please stay tuned :)

**Comment by EnixCoda** [comment]
Support for large repositories will arrive with `lazy mode`, which will be shipped with `v2.4.0` and is under review now. Feel free to reopen this issue if anything goes wrong again.

Thanks to this issue, I refactored the core module of Gitako so that it is much more robust than before! 😄
