### ISSUE TITLE
[Bug report]"Copy file shortcut" and "Copy snippet shortcut" Error

### ISSUE THREAD

**Issue by Higurashi-kagome** [EnixCoda/Gitako#99]
Hi👋

It seems that there are some issues with the copy part:

1. I can't copy the snippet successfully and the copy file button display failed.

    <details>
			<summary><strong>copy the snippet and the copy file button display</strong></summary>

    ![back problem6](https://user-images.githubusercontent.com/51501079/98644669-cd6ede00-236b-11eb-9c3f-6b4f189fde30.gif)

    </details>

2. Copy file button displayed well after refreshing the page, but it can't copy the file content successfully too.

    <details>
			<summary><strong>copy file content</strong></summary>

    ![back problem7](https://user-images.githubusercontent.com/51501079/98645381-d57b4d80-236c-11eb-8c90-bfeb62687cee.gif)

    </details>

Thanks!

**Comment by EnixCoda** [comment]
Hi @liuhao326  Thank you for reporting this issue!

This is quite serious a problem to users. I'll work on it ASAP.

**Comment by EnixCoda** [comment]
It seem that this is broke by the previous *no breaking change* update of react 17, as [react changed its root element of event delegation.](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation)

Although I've read the changelog immediately when it was published, did not expect that it could impact on Gitako's button until this issue. We may never be too careful of taking a leap forward. 🤔

Will be fixed in next patch release.

**Comment by EnixCoda** [comment]
Fixed in `v2.4.1`

**Comment by Higurashi-kagome** [comment]
Thanks!
